CREATE TABLE IF NOT EXISTS `wp_counry` (
  `country_id` int(8) NOT NULL AUTO_INCREMENT,
  `country_name` varchar(255) NOT NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE KEY `country_id` (`country_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=241 ;

INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(1, 'United States');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(2, 'United States Minor Outlying Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(3, 'Albania');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(4, 'Algeria');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(5, 'American Samoa');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(6, 'Andorra');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(7, 'Angola');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(8, 'Anguilla');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(9, 'Antarctica');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(10, 'Antigua and Barbuda');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(11, 'Argentina');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(12, 'Armenia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(13, 'Aruba');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(14, 'Australia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(15, 'Austria');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(16, 'Azerbaijan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(17, 'Bahamas');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(18, 'Bahrain');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(19, 'Bangladesh');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(20, 'Barbados');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(21, 'Belarus');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(22, 'Belgium');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(23, 'Belize');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(24, 'Benin');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(25, 'Bermuda');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(26, 'Bhutan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(27, 'Bolivia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(28, 'Bosnia And Herzegovina');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(29, 'Botswana');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(30, 'Bouvet Island');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(31, 'Brazil');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(32, 'British Indian Ocean Territory');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(33, 'Brunei Darussalam');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(34, 'Bulgaria');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(35, 'Burkina Faso');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(36, 'Burundi');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(37, 'Cambodia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(38, 'Cameroon');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(39, 'Canada');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(40, 'Cape Verde');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(41, 'Cayman Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(42, 'Central African Republic');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(43, 'Chad');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(44, 'Chile');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(45, 'China');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(46, 'Christmas Island');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(47, 'Cocos (Keeling) Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(48, 'Colombia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(49, 'Comoros');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(50, 'Congo');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(51, 'Congo The Democratic Republic Of The');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(52, 'Cook Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(53, 'Costa Rica');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(54, 'Cote D''ivoire');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(55, 'Croatia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(56, 'Cuba');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(57, 'Cyprus');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(58, 'Czech Republic');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(59, 'Denmark');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(60, 'Djibouti');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(61, 'Dominica');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(62, 'Dominican Republic');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(63, 'East Timor');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(64, 'Ecuador');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(65, 'Egypt');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(66, 'El Salvador');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(67, 'GEquatorial Guinea');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(68, 'Eritrea');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(69, 'Estonia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(70, 'Ethiopia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(71, 'Falkland Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(72, 'Faroe Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(73, 'Fiji');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(74, 'Finland');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(75, 'France');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(76, 'French Guiana');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(77, 'French Polynesia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(78, 'French Southern Territories');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(79, 'Gabon');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(80, 'Gambia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(81, 'Georgia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(82, 'Germany');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(83, 'Ghana');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(84, 'Gibraltar');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(85, 'Greece');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(86, 'Greenland');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(87, 'Grenada');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(88, 'Guadeloupe');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(89, 'Guam');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(90, 'Guatemala');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(91, 'Guinea');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(92, 'Guinea-bissau');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(93, 'Guyana');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(94, 'Haiti');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(95, 'Heard Island And Mcdonald Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(96, 'Holy See');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(97, 'Honduras');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(98, 'Hong Kong');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(99, 'Hungary');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(100, 'Iceland');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(101, 'India');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(102, 'Indonesia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(103, 'Iran');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(104, 'Iraq');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(105, 'Ireland');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(106, 'Israel');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(107, 'Italy');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(108, 'Jamaica');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(109, 'Japan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(110, 'Jordan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(111, 'Kazakstan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(112, 'Kenya');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(113, 'Kiribati');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(114, 'Korea Democratic People''s Republic Of');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(115, 'Korea');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(116, 'Kosovo');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(117, 'Kuwait');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(118, 'Kyrgyzstan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(119, 'Lao People''s Democratic Republic');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(120, 'Latvia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(121, 'Lebanon');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(122, 'Lesotho');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(123, 'Liberia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(124, 'Libyan Arab Jamahiriya');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(125, 'Liechtenstein');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(126, 'Lithuania');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(127, 'Luxembourg');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(128, 'Macau');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(129, 'Macedonia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(130, 'Madagascar');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(131, 'Malawi');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(132, 'Malaysia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(133, 'Maldives');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(134, 'Mali');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(135, 'Malta');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(136, 'Marshall Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(137, 'Martinique');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(138, 'Mauritania');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(139, 'Mauritius');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(140, 'Mayotte');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(141, 'Mexico');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(142, 'Micronesia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(143, 'Moldova');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(144, 'Monaco');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(145, 'Mongolia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(146, 'Montserrat');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(147, 'Montenegro');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(148, 'Morocco');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(149, 'Mozambique');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(150, 'Myanmar');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(151, 'Namibia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(152, 'Nauru');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(153, 'Nepal');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(154, 'Netherlands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(155, 'Netherlands Antilles');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(156, 'New Caledonia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(157, 'New Zealand');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(158, 'Nicaragua');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(159, 'Niger');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(160, 'Nigeria');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(161, 'Niue');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(162, 'Norfolk Island');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(163, 'Northern Mariana Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(164, 'Norway');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(165, 'Oman');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(166, 'Pakistan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(167, 'Palau');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(168, 'Palestinian Territory');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(169, 'Panama');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(170, 'Papua New Guinea');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(171, 'Paraguay');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(172, 'Peru');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(173, 'Philippines');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(174, 'Pitcairn');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(175, 'Poland');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(176, 'Portugal');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(177, 'Puerto Rico');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(178, 'Qatar');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(179, 'Reunion');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(180, 'Romania');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(181, 'Russian Federation');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(182, 'Rwanda');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(183, 'Saint Helena');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(184, 'Saint Kitts And Nevis');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(185, 'Saint Lucia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(186, 'Saint Pierre And Miquelon');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(187, 'Saint Vincent And The Grenadines');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(188, 'Samoa');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(189, 'San Marinov');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(190, 'Sao Tome And Principe');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(191, 'Saudi Arabia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(192, 'Senegal');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(193, 'Serbia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(194, 'Seychelles');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(195, 'Sierra Leone');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(196, 'Singapore');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(197, 'Slovakia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(198, 'Slovenia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(199, 'Solomon Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(200, 'Somalia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(201, 'South Africa');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(202, 'South Georgia and The South Sandwich Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(203, 'Spain');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(204, 'Sri Lanka');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(205, 'Sudan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(206, 'Suriname');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(207, 'Svalbard And Jan Mayen');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(208, 'Swaziland');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(209, 'Sweden');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(210, 'Switzerland');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(211, 'Syrian Arab Republic');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(212, 'Taiwan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(213, 'Tajikistan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(214, 'Tanzania');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(215, 'Thailand');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(216, 'Togo');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(217, 'Tokelau');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(218, 'Tonga');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(219, 'Trinidad And Tobago');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(220, 'Tunisia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(221, 'Turkey');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(222, 'Turkmenistan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(223, 'Turks And Caicos Islands');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(224, 'Tuvalu');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(225, 'Uganda');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(226, 'Ukraine');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(227, 'United Arab Emirates');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(228, 'United Kingdom');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(229, 'Uruguay');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(230, 'Uzbekistan');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(231, 'Vanuatu');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(232, 'Venezuela');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(233, 'Vietnam');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(234, 'Virgin Islands British');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(235, 'Virgin Islands U.S.');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(236, 'Wallis And Futuna');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(237, 'Western Sahara');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(238, 'Yemen');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(239, 'Zambia');
INSERT INTO `wp_counry` (`country_id`, `country_name`) VALUES(240, 'Zimbabwe');
